### ISSUE TITLE
Change the Status bar in subdomains in two status bars

### ISSUE THREAD

**Issue by overeha** [code4romania/civiclabs.ro#47]
The status bar currently available in the subdomains pages needs to be split in two. 
On the left a status bar  with percentages (i have to be able to select the percentage in the admin dashboard in the subdomain page). Title: RO: Cercetare EN: Research
On the right a status bar with percentages (i have to be able to select the percentage in the admin dashboard in the subdomain page). Title RO: Prototipare EN: Prototyping

**Comment by overeha** [comment]
I changed this issue to urgent also. Please prioritise it too. Thank you.

**Comment by overeha** [comment]
I need two status bars in the subdomains pages: 
Titles:
Cercetare/Research
Prototipare/Prototyping

I need to be able to set the percentages (can be a progression with a 5% point, aka i need to input 10,15,20,25,30,35 etc)

![simulare CL - status bars](https://user-images.githubusercontent.com/45068169/74828679-331bc580-5318-11ea-9a8c-f3997ba2d211.png)

**Comment by cosminbosutar** [comment]
@overeha please have a look at the pictures to see if it is ok.
![image](https://user-images.githubusercontent.com/47278224/78069249-7307ab00-73a2-11ea-9926-74a730863986.png)

![image](https://user-images.githubusercontent.com/47278224/78069311-8e72b600-73a2-11ea-974e-aecd11123d4d.png)

![image](https://user-images.githubusercontent.com/47278224/78069477-d98cc900-73a2-11ea-8f9b-2e482d675ba6.png)

**Comment by cosminbosutar** [comment]
@overeha, @andreiio this has already been delivered.

Can we close the issue?
Is there something else left to do?
