### ISSUE TITLE
Create Applicant user account

### ISSUE THREAD

**Issue by overeha** [code4romania/civiclabs.ro#48]
Currently I have three types of accounts in CIvic Labs: 
- Admin (Code for Romania)
- Financer (for companies adopting solutions) 
- Juror (for people who need to evaluate applications)

I need another account type
**Name: Applicant**
with the following features: 
- automatic account creation - if I am an Applicant and I want to fill in a form to apply to a call I want to be able to create an account by inputting my email address and receiving a password setting e-mail 
- a dashboard where I can see my application and the status of it (open call, under review, approved or rejected)

**Comment by cosminbosutar** [comment]
Sub-tasks/Questions:
- Registration needs to be activated;
- A new user type need to be added to the DB
- Statuses for "applications" need to be set up
    - Which are the statuses?
- Dashboard view/views need to be created for "applications"
- Both "I want to finance this project(Vreau să finanțez acest proiect)" and "I want to implement this project(Vreau să implementez acest proiect)" need to be active all the time?
- A register modal needs to be created
    - What about the NGOs that already have an account?
        - Should they be redirected to the login page?
        - Should an NGO be able to apply after login?
            - If "Yes" then new "Solutions" screens need to be created inside the NGO Dashboard

@overeha how should we proceed?

**Comment by overeha** [comment]
Sub-tasks/Questions:
- Registration needs to be activated; - yes
- A new user type need to be added to the DB - yes
- Statuses for "applications" need to be set up
- Which are the statuses?  Aplicație primită (Received)/Aplicație în jurizare(Evaluation)/Aplicație respinsă(Rejected)
- Dashboard view/views need to be created for "applications" - this is the dashboard that the apllicant can see in his account. It can be the same as a juror view, that we currently have designed. 
The dashboard for the applicant should let me see two lists - solutions i am interested in and solutions i have applied to. 

- Both "I want to finance this project(Vreau să finanțez acest proiect)" and "I want to implement this project(Vreau să implementez acest proiect)" need to be active all the time? - replied in a different issue to this 
- A register modal needs to be created
- What about the NGOs that already have an account?
- Should they be redirected to the login page?
- Should an NGO be able to apply after login?
- If "Yes" then new "Solutions" screens need to be created inside the NGO Dashboard - please see the other issue for all of the above.
