### ISSUE TITLE
Create I'm interested counter

### ISSUE THREAD

**Issue by overeha** [code4romania/civiclabs.ro#49]
Under every prototype I currently have a "I want to implement this project" button. 
This button is available only when an app is in Open Call status. I need it to be available all the time and have the label "Sunt interesat/I'm interested". 

If I am an NGO and I am interested in that app, upon clicking the button I will be prompted with a form where I can input my NGO name and my e-mail address. I also need to have an option (checkbox) asking me if I also want to create an account for Civic Labs. 

If the checkbox is ticked I will receive an e-mail with a standard message and a link to set my password for my account

If the checkbox is not ticked, I will receive an automated e-mail with a standard message informing me I have been subscribed to the newsletter and other details.

**Comment by cosminbosutar** [comment]
The counter can be implemented individually (1) or together withe NGO accounts.
(1) The counter will be linked only by the solution and we can create the popup will be used only for the newsletter subscription
(2) the counter is created after the NGo accounts are available and we can include the signup feature as well:

Questions:
- Both "I want to finance this project(Vreau să finanțez acest proiect)" and "I want to implement this project(Vreau să implementez acest proiect)" need to be active all the time?
- A new modal needs to be created
    - What about the NGOs that already have an account?
        - Should they be redirected to the login page?
        - Should an NGO be able to apply after login?
            - If "Yes" then new "Solutions" screens need to be created inside the NGO Dashboard

@overeha how should we proceed?

**Comment by overeha** [comment]
Both "I want to finance this project(Vreau să finanțez acest proiect)" should be active as long as the project is set as "Neadoptat"
"I want to implement this project(Vreau să implementez acest proiect)" needs to be active as long as there is no "Implementat de/Implemented by" NGO selected for the solution. 

NGOs that already have an account:
- yes, they should be redirected to login if they already have an account
- i do not understand the second question (let's talk about this during a call tomorrow)
