### ISSUE TITLE
Change solution status bar behavior

### ISSUE THREAD

**Issue by overeha** [code4romania/civiclabs.ro#50]
Currently my solutions have several statuses. Open Call, Under review, Implementation etc. 

I want to have three different statuses for my solutions and they are visible only if one of the statuses is selected. The new statuses are: Adopted, Available, Live project (Adoptat, Neadoptat, Proiect live)

**Comment by cosminbosutar** [comment]
I made the changes and tested them locally.

After the deploy will be performed, all solutions will lose their status and a manual update needs to be performed for all of them.

I need help with the deploy configuration.

**Comment by andreiio** [comment]
Open a PR and I can deploy it once we merge.
