### ISSUE TITLE
Create interested NGOs bar 

### ISSUE THREAD

**Issue by overeha** [code4romania/civiclabs.ro#51]
In the solution page, under the header I want to have a stripe with logos. 
If the solution status is Available, then I want the bar to feature all the NGOs who ticked I'm Interested to show up there. 
If the solution status is Adopted, then I want the bar to be split in two - on the left I will have "Solution adopted by:" and the financer logo. On the right I will have "Implemented by" and the winning NGO logo. 

I should be able to add all the interested NGOs logos somewhere in the dashboard ( perhaps in the solution admin page) Ideally, once an NGO marks itself as interested, it can already show in a dedicated section in the admin dashboard.

**Comment by cosminbosutar** [comment]
This can be developped after the NGO accounts are available (1) or before the NGO accounts are available (2).
(1) After the NGO accounts are available, the process of extraction the NGO's logo can be automatised.
(2) Before the NGO accounts are available, we can implement first version in which the logos are added manually in the solution admin page.

@overeha how should we proceed?

**Comment by overeha** [comment]
Under the solution header i need to see a bar split in two sections: 
the ratio should be: 1/3 (the first section of the bar should be shorter (see the simulation below).
 
**1. the first section of the bar will display:**
    a.  ”Finanțat de/Financed by:” and the funder logo if the solution is adopted. 
    b. ”Vrei să finanțezi acest proiect?/ Do you want to fund this project?” if the solution is not adopted yet. The text should link to the standard pop-up that now shows when you click on the dedicated button under the prototype. (please see screenshot below.)

**2. the second section of the bar will display:** 
    a. ”Ong-uri interesate/Interested NGOs:” and the ngo logos if the solution has not been granted yet a winner. (granting a solution to an NGO has to be done manually, just as we do it now in the solution page - see screenshot below)
    b. ”Implementat de:/Implemented by:” and the winning NGO logo if the NGO has been granted the solution

![simulare ecran CL](https://user-images.githubusercontent.com/45068169/74535280-27a65400-4f3e-11ea-8698-3731ffe4336b.png)

Pop-up for funders:
![image](https://user-images.githubusercontent.com/45068169/74535663-fb3f0780-4f3e-11ea-8bc0-a7edd0072264.png)

Admin view where I select the winning NGO
![image](https://user-images.githubusercontent.com/45068169/74535783-40633980-4f3f-11ea-9cbe-4241ce821266.png)

**Comment by andreiio** [comment]
Implemented in #73
