### ISSUE TITLE
Create form option for all pages

### ISSUE THREAD

**Issue by overeha** [code4romania/civiclabs.ro#53]
I need to be able to create forms regardless of where I am in the platform (for example, I want to be able to add a form in a content page and to be able to choose on what e-mail will I receive the information sent through that form.

**Comment by cosminbosutar** [comment]
@andreiio @overeha is the example scenario implemented anywhere?

**Comment by andreiio** [comment]
It isn't implemented, but the closest thing is the ApplicationForm model, which uses a [vue component](https://github.com/code4romania/civiclabs.ro/blob/ae87e035ec4184bc610e2f529e6de246dffeba98/resources/assets/js/components/ApplicationForm.vue) to display the form blocks.
